import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import {
  IsEmail,
  IsIn,
  IsNotEmpty,
  IsString,
  MaxLength,
  MinLength,
} from 'class-validator';
import { Transform } from 'class-transformer';
// UserRole values: 'admin' | 'super_admin'

/**
 * Payload for creating a new admin account.
 * The password is auto-generated by the service and sent to the provided email —
 * it is therefore NOT part of this DTO.
 */
export class CreateAdminDto {
  @ApiProperty({ example: 'admin@example.com', description: 'Admin email address' })
  @IsEmail({}, { message: 'Please provide a valid email address' })
  @Transform(({ value }: { value: string }) => value?.toLowerCase().trim())
  email: string;

  @ApiProperty({ example: 'Jane Doe', description: 'Full display name' })
  @IsString()
  @IsNotEmpty({ message: 'Name is required' })
  @MinLength(2, { message: 'Name must be at least 2 characters long' })
  @MaxLength(100, { message: 'Name must not exceed 100 characters' })
  @Transform(({ value }: { value: string }) => value?.trim())
  name: string;

  @ApiPropertyOptional({
    enum: ['admin', 'super_admin'],
    default: 'admin',
    description: 'Role assigned to the new admin',
  })
  @IsIn(['admin', 'super_admin'], {
    message: 'Role must be admin or super_admin',
  })
  role?: string = 'admin';

  // Password field used when creating both AdminUser and User records
  password?: string;
}
