import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { IsInt, IsNotEmpty, IsOptional, IsString, IsUrl, Min } from 'class-validator';

export class TelegramAuthDto {
  @ApiProperty({ description: 'Telegram user ID', example: 123456789 })
  @IsInt()
  @Min(1)
  id: number;

  @ApiProperty({ description: 'Telegram user first name', example: 'Jane' })
  @IsString()
  @IsNotEmpty()
  first_name: string;

  @ApiPropertyOptional({ description: 'Telegram username', example: 'janed' })
  @IsOptional()
  @IsString()
  username?: string;

  @ApiPropertyOptional({ description: 'Telegram profile photo URL' })
  @IsOptional()
  @IsUrl()
  photo_url?: string;

  @ApiProperty({
    description: 'Unix timestamp of authentication (must be within 1 hour)',
    example: 1718000000,
  })
  @IsInt()
  @Min(0)
  auth_date: number;

  @ApiProperty({
    description: 'HMAC-SHA256 hash generated by the Telegram login widget',
  })
  @IsString()
  @IsNotEmpty()
  hash: string;
}
